### ISSUE TITLE
v1.5 and v1.6 roadmap

### ISSUE THREAD

**Issue by dec4234** [dec4234/JavaDestinyAPI#17]
v1.5
- [x] **BungieUser Profiles**
        Each BungieUser could correspond to multiple bungie profiles that are all equally valid. BungieUser should be reworked to include a List of valid DestinyUserProfiles.
- [x] **Return List of DestinyProfiles in user searching**
        For the same reasons as above, when searching for a user it could come up with multiple valid profiles pointing to the same user. The search methods should return a List of valid profiles.
- [x] **Rework getMembers() system**
        All of the getMembers() methods in the Clan class need to be combined down to one method. They should exclusively return a List of ClanMembers rather than BungieUser. Remove the entire async splitting architecture, as it isn't very beneficial anymore.
- [x] **Iteration options for searching**
        Thanks to the suggestion in #16 the search methods should be at least partially reworked to include iteration options for the end-user. This could potentially improve search times in some cases.
- [x] **Add getOldestMembers() to Clan**
        Use code from Benedict 99-40 to add a getOldestMembers() call, which returns a list of the oldest members in the clan.

v1.6
- [ ] **Continue Work On Activities**
        Pick up where we left off with the Activity and related scraping system.
- [ ] **Continue work on Inventory and Collections Management**
        Only partially complete, still missing some very important things.
- [ ] **Implement system to use cached manifest file**
        Instead of downloading the entire JSON Object or making individual calls, we can save the manifest file if the user wants and use SQL to get the manifest items.
